(function(b){var c=function(){};c.test=document.createElement("div");c.isEmpty=function(b){return 0==b.replace(/^\s+|\s+$/g,"").length};c.strip=function(b){return b.replace(/^\s+|\s+$/g,"")};c.isNumber=function(b){return!isNaN(parseFloat(b))&&isFinite(b)};c.isMobile=function(){return/Android|webOS|iPhone|iPad|iPod|sony|BlackBerry/i.test(navigator.userAgent)};c.isIE=function(){return-1!=c.getInternetExplorerVersion()?!0:!1};c.isChrome=function(){return!!b.chrome&&!!b.chrome.webstore};c.getInternetExplorerVersion=
function(){var b=-1;if("Microsoft Internet Explorer"==navigator.appName){var c=navigator.userAgent,w=/MSIE ([0-9]{1,}[.0-9]{0,})/;null!=w.exec(c)&&(b=parseFloat(RegExp.$1))}else"Netscape"==navigator.appName&&(c=navigator.userAgent,w=/Trident\/.*rv:([0-9]{1,}[.0-9]{0,})/,null!=w.exec(c)&&(b=parseFloat(RegExp.$1)));return b};c.isIOS=function(){return navigator.userAgent.match(/(iPad|iPhone|iPod)/g)};c.isAndroid=function(){return-1<navigator.userAgent.indexOf("Android")};c.hasDownloadSupport=function(){return"download"in
document.createElement("a")};c.volumeCanBeSet=function(){var b=document.createElement("audio");if(!b)return!1;b.volume=0;return 0==b.volume?!0:!1};c.supportsWebGL=function(){try{return!!b.WebGLRenderingContext&&!!document.createElement("canvas").getContext("experimental-webgl")}catch(q){return!1}};c.relativePath=function(b){return/^(?:[a-z]+:)?\/\//i.test(b)};c.qualifyURL=function(b){var c=document.createElement("a");c.href=b;return c.href};c.hasFullscreen=function(){return c.test.requestFullscreen||
c.test.mozRequestFullScreen||c.test.msRequestFullscreen||c.test.oRequestFullscreen||c.test.webkitRequestFullScreen};c.selectText=function(c){var z=document;if(z.body.createTextRange)z=z.body.createTextRange(),z.moveToElementText(c),z.select();else if(b.getSelection){var q=b.getSelection();z=z.createRange();z.selectNodeContents(c);q.removeAllRanges();q.addRange(z)}};c.randomiseArray=function(b){var c=[],q=[],F;for(F=0;F<b;F++)c[F]=F;for(F=0;F<b;F++){var m=Math.round(Math.random()*(c.length-1));q[F]=
c[m];c.splice(m,1)}return q};c.sortArray=function(b,c){var q,z=b.length,m=[];for(q=0;q<z;q++)m[q]=b[c[q]];return m};c.keysrt=function(b,c,w){var q=1;w&&(q=-1);return b.sort(function(b,f){var m=b[c],d=f[c];return q*(m<d?-1:m>d?1:0)})};c.formatCurrentTime=function(b){b=Math.round(b);var c=Math.floor(b/60);b=Math.floor(b%60);return(10<=c?c:""+c)+":"+(10<=b?b:"0"+b)};c.formatDuration=function(b){b=Math.round(b);var c=Math.floor(b/60);b=Math.floor(b%60);return(10<=c?c:""+c)+":"+(10<=b?b:"0"+b)};c.toSeconds=
function(b){b=b.split(/[\.:,]+/);return Number(3600*+b[0]+60*+b[1]+ +b[2])};b.MVPUtils=c})(window);
(function(b,c){b.MVPYoutubeLoader=function(b){function z(){if(d.length){r=d.shift();f=r.type;var b=r.path;M=0;v=1;D=r.limit||200;B=r.order||"relevance";-1==c.inArray(B,Z)&&(B="relevance");if("youtube_single"==f||"youtube_single_list"==f)b="https://www.googleapis.com/youtube/v3/videos?id="+b+"&key="+H+"&part=snippet,contentDetails,statistics,status";else if("youtube_playlist"==f)b="https://www.googleapis.com/youtube/v3/playlistItems?part=snippet,status,contentDetails&maxResults=50&playlistId="+b+"&key="+
H;else if("youtube_video_query"==f)b="https://www.googleapis.com/youtube/v3/search?part=id,snippet&type=video&maxResults=50&order="+B+"&q="+b+"&key="+H;else if("youtube_channel"==f)ma=b,b="https://www.googleapis.com/youtube/v3/search?part=id,snippet&order=date&maxResults=50&order=date&channelId="+ma+"&key="+H;else{console.log("Wrong youtube type!");return}q(b)}else c(m).trigger("MVPYoutubeLoader.END_LOAD",[I])}function q(b){c.ajax({url:b,dataType:"jsonp"}).done(function(b){b.error&&b.error.message&&
console.log(b.error.message);var c,d=b.items.length,m;d+M>D&&(d=D-M);for(c=0;c<d;c++)(m=b.items[c])&&("youtube_playlist"==f||"youtube_single"==f||"youtube_single_list"==f?"private"!=m.status.privacyStatus&&(m.snippet.title?"Deleted video"!=m.snippet.title:1)&&I.push(F(m,f)):("youtube_video_query"==f||"youtube_channel"==f)&&I.push(F(m,f)));if("youtube_single"==f||"youtube_single_list"==f)z();else if(v+=50,v<D)if(v<=b.pageInfo.totalResults&&b.nextPageToken){c=r.path;if("youtube_playlist"==f)var w="https://www.googleapis.com/youtube/v3/playlistItems?pageToken="+
b.nextPageToken+"&part=snippet,status,contentDetails&maxResults=50&playlistId="+c+"&key="+H;else"youtube_video_query"==f?w="https://www.googleapis.com/youtube/v3/search?pageToken="+b.nextPageToken+"&part=id,snippet&maxResults=50&order="+B+"&q="+c+"&key="+H:"youtube_channel"==f&&(w="https://www.googleapis.com/youtube/v3/search?pageToken="+b.nextPageToken+"&part=id,snippet&maxResults=50&order=date&channelId="+ma+"&key="+H);q(w)}else z();else z()}).fail(function(b,c,d){console.log(b,c,d);z()})}function F(b,
c){var d=jQuery.extend(!0,{},r);d.type="youtube";d.deeplink&&"youtube_single"!=d.origtype&&(d.deeplink+=(M+1).toString(),M++);if("youtube_single"==c||"youtube_single_list"==c)d.id=b.id;else if("youtube_playlist"==c)d.id=b.contentDetails.videoId;else if("youtube_video_query"==c||"youtube_channel"==c)d.id=b.id.videoId;!d.title&&b.snippet.title&&(d.title=b.snippet.title);!d.description&&b.snippet.description&&(d.description=b.snippet.description);!d.thumb&&b.snippet.thumbnails&&(b.snippet.thumbnails.medium?
d.thumb=b.snippet.thumbnails.medium.url:b.snippet.thumbnails["default"]?d.thumb=b.snippet.thumbnails["default"].url:b.snippet.thumbnails.standard&&(d.thumb=b.snippet.thumbnails.standard.url));d.share||(d.share="https://www.youtube.com/watch?v="+d.id);return d}var m=this,f,r,d=[],I=[],ma,M,v,D,B,Z="date rating relevance title videoCount viewCount".split(" "),H=b.youtubeAppId;this.setData=function(b){!H||MVPUtils.isEmpty(H)?alert("Youtube API key missing! Set API key in settings."):(I=[],d=c.extend(!0,
[],[b]),z())}}})(window,jQuery);
(function(b,c){b.MVPPlaylistManager=function(b){function z(){v=MVPUtils.randomiseArray(f)}var w=this,F=b.loopingOn,m=b.randomPlay,f,r=!1,d=-1,I,q,M=!1,v=[],D=!1;this.setCounter=function(b,q){"undefined"===typeof q&&(q=!0);d=q?d+parseInt(b,10):parseInt(b,10);if(isNaN(d))alert("MVPPlaylistManager message: No active media, counter = "+d);else if(r=!1,F){if(m)if(d>f-1){d=v[f-1];z();if(v[0]==d){var B=v.splice(0,1);v.push(B)}d=0}else 0>d&&(d=v[0],z(),v[f-1]==d&&(B=v.splice(f-1,1),v.unshift(B)),d=f-1);else d>
f-1?d=0:0>d&&(d=f-1);c(w).trigger("MVPPlaylistManager.COUNTER_READY",d)}else d>f-1?(d=f-1,r=!0):0>d&&(d=0),r?c(w).trigger("MVPPlaylistManager.PLAYLIST_END"):c(w).trigger("MVPPlaylistManager.COUNTER_READY",d)};this.getCounter=function(){return m?D?d:v[d]:d};this.advanceHandler=function(b){D=!1;M?(M=!1,q+b>f-1?(d=f-1,c(w).trigger("MVPPlaylistManager.COUNTER_READY",d)):0>q+b?(d=0,c(w).trigger("MVPPlaylistManager.COUNTER_READY",d)):w.setCounter(q+b,!1)):w.setCounter(b)};this.processPlaylistRequest=function(b){D=
!1;m&&(D=!0,I=b,M||(q=d,M=!0));w.setCounter(b,!1)};this.setPlaylistItems=function(b,c){"undefined"===typeof c&&(c=!0);c&&(d=-1);f=b;m&&z()};this.reSetCounter=function(b){"undefined"===typeof b?d=-1:(b=parseInt(b,10),f?(b>f-1?b=f-1:0>b&&(b=0),d=b):d=-1)};this.setRandom=function(b){(m="undefined"!==typeof b?b:!m)&&z();if(m){var c=v.length;for(b=0;b<c;b++)if(v[b]==d){if(0==b)break;b=v.splice(b,1);v.unshift(parseInt(b,10));break}d=0}else M?(d=I,M=!1):d=v[d]};this.setLooping=function(b){F="undefined"!==
typeof b?b:!F};this.getPosition=function(b){return v.indexOf(b)}}})(window,jQuery);
(function(b,c){function q(b,c,f,r){var d={},m=f.width();f=f.height();r=z(c,r);c=r.width;r=r.height;var q=(m-0)/(f-0),F=c/r;F<q?b?(d.width=(f-0)/r*c,d.height=f-0):(d.height=(m-0)/c*r,d.width=m-0):F>q?b?(d.height=(m-0)/c*r,d.width=m-0):(d.width=(f-0)/r*c,d.height=f-0):(d.width=m-0,d.height=f-0);return d}function z(b,c){var f={};"video"==b?c.videoWidth&&c.videoHeight?(f.width=c.videoWidth,f.height=c.videoHeight):c[0]&&c[0].videoWidth&&c[0].videoHeight?(f.width=c[0].videoWidth,f.height=c[0].videoHeight):
(f.width=640,f.height=360):"youtube"==b||"vimeo"==b?c.sw&&c.sh?(f.width=c.sw,f.height=c.sh):(f.width=640,f.height=360):"image"==b&&(f.width=c.width(),f.height=c.height());return f}var w=function(){};w.resizeMedia=function(b,c,f,r){var d,m=f.width();var w=f.height();0==c?d=z(b,r):1==c?d=q(!0,b,f,r):2==c&&(d=q(!1,b,f,r));b=parseInt((m-d.width)/2,10);w=parseInt((w-d.height)/2,10);r.css({width:d.width+"px",height:d.height+"px",left:b+"px",top:w+"px"})};b.MVPAspectRatio=w})(window,jQuery);
(function(b,c){b.MVPImageZoom=function(c){var q,w;function F(b){0<(0<b.originalEvent.deltaY?-1:1)?qb(1.1):(D>Z+1||B>H+1)&&qb(.9);return!1}function m(){oa.on("pan",function(b){(D>Z+1||B>H+1)&&xa(b.deltaX,b.deltaY)});oa.on("panend",function(b){Qa=ha;Ra=ia});oa.on("pinch",function(b){null===P&&(P=rb(b),q=P.x*t-(-ha*t+Math.min(Z,D)/2),w=P.y*t-(-ia*t+Math.min(H,B)/2));var c=Fa(t*b.scale);aa(b.scale,(P.x*c-q)/c,(P.y*c-w)/c,!0)});oa.on("pinchend",function(b){Ea=t;Qa=ha;Ra=ia;P=null});oa.on("doubletap",function(b){b=
rb(b);1!=t?aa(1.3,b.x,b.y):f.resizeImage()});if(!r)I.on("wheel",F)}var f=this,r=MVPUtils.isMobile(),d=c,I=c.holder,ma,M=null,v=null,D,B,Z=null,H=null,Gb,na,Da,t=null,Ea=null,O=null,ha=0,ia=0,Qa=0,Ra=0,P=null;this.initMedia=function(b){"undefined"!==typeof b&&(d=b);O=d.image[0];Gb=d.fullImageWidth;na=d.fullImageHeight;O.style.height="auto";M=O.width;v=O.height;Da=Gb/na;Z=I.width();H=I.height();Ea=t=v/na;D=M*t;B=v*t;ya();f.resizeImage();ma=t;m()};this.resize=function(){Z=I.width();H=I.height();f.resizeImage();
ma=t};this.zoomCustom=function(){1!=t?qb(1.3):f.resizeImage()};this.resizeImage=function(){var b=I.width(),c=I.height();var d=b/c;if(Da<d){var f=c;f>na&&(f=na)}else Da>d?(f=na,f>c&&(f=Da*c>b?b/Da:c)):f=c;O.style.height=f+"px";d=parseInt(O.width,10);b=parseInt((b-d)/2,10);c=parseInt((c-f)/2,10);O.style.left=b+"px";O.style.top=c+"px";Ea=t=f/na;D=d;B=f;xa(0,0)};var ya=function(){"onclick onmousedown onmousemove onmouseout onmouseover onmouseup ondblclick onfocus onblur".split(" ").forEach(function(b){O[b]=
function(){return!1}})},Fa=function(b){b<ma?b=ma:1<=b&&(b=1);return b},Sa=function(b,c,d){b<c/t-d?b=c/t-d:0<b&&(b=0);return b},xa=function(b,c){var d=Sa(Qa+b/t,Math.min(Z,D),M);ha=d;var f=I.width(),m=I.height();O.style.left=D>f?Math.ceil(d*t)+"px":Math.ceil(f/2-D/2)+"px";ia=d=Sa(Ra+c/t,Math.min(H,B),v);O.style.top=B>m?Math.ceil(d*t)+"px":Math.ceil(m/2-B/2)+"px"},rb=function(c){for(var d=null,f=0,m=0;null!==d;)f+=d.offsetLeft,m+=d.offsetTop,d=d.offsetParent;return{x:-ha+(c.center.x-f+(b.pageXOffset?
b.pageXOffset:document.body.scrollLeft))/t,y:-ia+(c.center.y-m+(b.pageYOffset?b.pageYOffset:document.body.scrollTop))/t}},aa=function(b,c,d,f){t=Fa(Ea*b);D=M*t;B=v*t;O.style.width=Math.ceil(D)+"px";O.style.height=Math.ceil(B)+"px";xa(0,0);xa((-ha+Math.min(Z,D)/2/t-c)*t,(-ia+Math.min(H,B)/2/t-d)*t);f||(Ea=t,Qa=ha,Ra=ia)},qb=function(b){aa(b,-ha+Math.min(Z,D)/2/t,-ia+Math.min(H,B)/2/t)},oa=new Hammer(I[0],{domEvents:!0});oa.get("pinch").set({enable:!0});oa.get("pan").set({direction:Hammer.DIRECTION_ALL});
this.deactivate=function(){oa.off("pan panend pinch pinchend doubletap");I.off("wheel");O.style.height="auto"};f.initMedia()}})(window,jQuery);
(function(b){b.fn.mvp=function(c){function q(a){if(l){if(!Hb){if("touchstart"==a.type){if(a=a.originalEvent.touches,!(a&&0<a.length))return!1}else a.preventDefault();Hb=!0;Y.on(pa,function(a){a:{if("touchmove"==a.type){if(a.originalEvent.touches&&a.originalEvent.touches.length)var b=a.originalEvent.touches;else if(a.originalEvent.changedTouches&&a.originalEvent.changedTouches.length)b=a.originalEvent.changedTouches;else break a;if(1<b.length)break a;b=b[0]}else b=a;a.preventDefault();z(b)}}).on(bb,
function(a){a:if(Hb){Hb=!1;Y.off(pa).off(bb);if("touchend"==a.type){if(a.originalEvent.touches&&a.originalEvent.touches.length)var b=a.originalEvent.touches;else if(a.originalEvent.changedTouches&&a.originalEvent.changedTouches.length)b=a.originalEvent.changedTouches;else break a;if(1<b.length)break a;b=b[0]}else b=a;a.preventDefault();z(b)}})}return!1}}function z(a){a=a.pageX-Ib.offset().left;0>a?a=0:a>ja&&(a=ja);a=Math.max(0,Math.min(1,a/ja));if("video"==h)try{g.currentTime=(a*g.duration).toFixed(1)}catch(qa){}else"youtube"==
h&&p.seekTo(a*p.getDuration())}function w(a){var b=a.pageX-Ib.offset().left;if(!MVPUtils.isNumber(b))return!1;0>b?b=0:b>ja&&(b=ja);b=Math.max(0,Math.min(1,b/ja));if(!MVPUtils.isNumber(b))return!1;var c=x[0].getBoundingClientRect(),d=za[0].getBoundingClientRect();a=parseInt(a.pageX-Ga.scrollLeft()-c.left-A.outerWidth()/2);c="top"==jd?parseInt(d.top-c.top+za.outerHeight()+10,10):parseInt(d.top-c.top-A.outerHeight(),10);0>a?a=0:a+A.outerWidth()>e.width()&&(a=e.width()-A.outerWidth());A.css({left:a+"px",
top:c+"px"}).show();if("video"==h)var f=g.duration;else"youtube"==h&&(f=p.getDuration());MVPUtils.isNumber(f)&&A.find("p").html(MVPUtils.formatCurrentTime(f*b)+" / "+MVPUtils.formatDuration(f))}function F(a){if(l){if(!Jb){if("touchstart"==a.type){if(a=a.originalEvent.touches,!(a&&0<a.length))return!1}else a.preventDefault();Jb=!0;Y.on(pa,function(a){a:{if("touchmove"==a.type){if(a.originalEvent.touches&&a.originalEvent.touches.length)var b=a.originalEvent.touches;else if(a.originalEvent.changedTouches&&
a.originalEvent.changedTouches.length)b=a.originalEvent.changedTouches;else break a;if(1<b.length)break a;b=b[0]}else b=a;a.preventDefault();f(b)}}).on(bb,function(a){a:if(Jb){Jb=!1;Y.off(pa).off(bb);if("touchend"==a.type){if(a.originalEvent.touches&&a.originalEvent.touches.length)var b=a.originalEvent.touches;else if(a.originalEvent.changedTouches&&a.originalEvent.changedTouches.length)b=a.originalEvent.changedTouches;else break a;if(1<b.length)break a;b=b[0]}else b=a;a.preventDefault();f(b)}})}return!1}}
function m(){if(!l)return!1;0<u?(gc=u,u=0):u=gc;r()}function f(a){Ta?u=Math.max(0,Math.min(1,(a.pageX-cb.offset().left)/db)):(u=Math.max(0,Math.min(1,(a.pageY-cb.offset().top)/db)),u=1-u);r()}function r(a){"undefined"!==typeof a&&(u=a);"undefined"!==typeof u&&("video"==h?(g.volume=u,g.muted=0==u?!0:!1):"youtube"==h&&(p.setVolume(100*u),0==u?p.mute():p.unMute()));eb.children().hide();0==u?eb.find(".mvp-volume-off").show():0<u&&.5>u?eb.find(".mvp-volume-down").show():.5<=u&&1>=u&&eb.find(".mvp-volume-up").show();
kd.css(Ta?"width":"height",u*db+"px");b(n).trigger("volumeChange",{instance:n,instanceName:J,volume:u})}function d(a){var b=Ta?a.pageX-cb.offset().left:a.pageY-cb.offset().top;0>b?b=0:b>db&&(b=db);b=Math.max(0,Math.min(1,b/db));if(!MVPUtils.isNumber(b))return!1;Ta||(b=1-b);b=parseInt(100*b,10);A.find("p").text(b+" %");var c=x[0].getBoundingClientRect(),d=V[0].getBoundingClientRect();Ta?(b=parseInt(a.pageX-Ga.scrollLeft()-c.left-A.outerWidth()/2),a=parseInt(d.top-c.top-A.outerHeight())):(b=parseInt(d.left-
c.left-A.outerWidth()/2+V.outerWidth()/2),a=parseInt(a.pageY-Ga.scrollTop()-c.top-A.outerHeight()-10));A.css({left:b+"px",top:a+"px"}).show()}function I(a){var b="https:"==window.location.protocol?"https:":"http:",c=(window.screen.width-600)/2,d=(window.screen.height-300)/2,f=E.find(".mvp-playlist-title").html(),e=E.find(".mvp-playlist-description").html(),h=E.find(".mvp-thumbimg").attr("src"),g=k.share||window.location.href,fb;MVPUtils.relativePath(h)||(h=MVPUtils.qualifyURL(k.thumb));"facebook"==
a?window.FB&&FB.ui({method:"share_open_graph",action_type:"og.shares",action_properties:JSON.stringify({object:{"og:url":g,"og:title":f,"og:description":e,"og:image":h}})},function(a){}):"twitter"==a?fb=b+"//twitter.com/intent/tweet?url="+encodeURIComponent(g)+"&text="+encodeURIComponent(f):"googleplus"==a?fb=b+"//plus.google.com/share?url="+encodeURIComponent(g):"tumblr"==a&&(fb=b+"//www.tumblr.com/share/link?url="+encodeURIComponent(g)+"&amp;name="+encodeURIComponent(f)+"&amp;description="+encodeURIComponent(e));
fb&&window.open(fb,"","menubar=no,toolbar=no,resizable=yes,scrollbars=yes,width=600,height=300,left="+c+",top="+d)}function ma(a){(function(a,b,c){var d=a.getElementsByTagName(b)[0];a.getElementById(c)||(a=a.createElement(b),a.id=c,a.src="//connect.facebook.net/en_US/sdk.js",d.parentNode.insertBefore(a,d))})(document,"script","facebook-jssdk");window.fbAsyncInit=function(){FB.init({appId:a,xfbml:!0,version:"v2.9"})}}function M(){if(b(this).hasClass("mvp-menu-active"))return!1;var a=b(this).attr("data-label");
"video"==h?g.playbackRate=Number(a):"youtube"==h&&p.setPlaybackRate(Number(a))}function v(a){hc&&hc.removeClass("mvp-menu-active");hc=ic.find(".mvp-menu-item[data-label='"+a+"']").addClass("mvp-menu-active")}function D(){var a=[],b=k.path.length;for(Aa=0;Aa<b;Aa++){var c=k.path[Aa];a.push(c.quality)}return a}function B(a,c){c||(c=Kb);var d,f=a.length;for(d=0;d<f;d++){var qa=a[d];var e=b("<li/>").addClass("mvp-menu-item").attr("data-label",qa).on("click",Z).appendTo(Lb);b('<a href="#"/>').text(qa).appendTo(e);
c==qa&&(Ha=e.addClass("mvp-menu-active"))}Mb.show()}function Z(){if(b(this).hasClass("mvp-menu-active"))return!1;Ha&&Ha.removeClass("mvp-menu-active");Ha=b(this).addClass("mvp-menu-active");var a=Ha.attr("data-label");k.quality=a;sb(!0)}function H(a){Ha&&Ha.removeClass("mvp-menu-active");Ha=Lb.find(".mvp-menu-item[data-label='"+a+"']").addClass("mvp-menu-active")}function Gb(){var a,c=k.subtitles.length;for(a=0;a<c;a++){var d=k.subtitles[a];var f=b("<li/>").addClass("mvp-menu-item").attr("data-label",
d.label).on("click",na).appendTo(Ua);b('<a href="#"/>').text(d.label).appendTo(f);d["default"]&&(Q=f.addClass("mvp-menu-active"),Da(d))}f=b("<li/>").addClass("mvp-menu-item").attr("data-label",Nb).on("click",na).appendTo(Ua);b('<a href="#"/>').text(Nb).appendTo(f);Q||(Q=f.addClass("mvp-menu-active"));Ob.show()}function na(){if(b(this).hasClass("mvp-menu-active"))return!1;Q&&Q.removeClass("mvp-menu-active");Q=b(this).addClass("mvp-menu-active");var a=Q.attr("data-label");n.setSubtitle(a)}function Da(a){ka=
[];b.ajax({url:a.src}).done(function(b){b=b.replace(/\r\n|\r|\n/g,"\n");b=MVPUtils.strip(b);b=b.split("\n\n");var c,d=0,f;for(c in b){var e=b[c].split("\n");if("WEBVTT"!=e){if(2<=e.length){var qa=MVPUtils.strip(e[1].split(" --\x3e ")[0]);var h=MVPUtils.strip(e[1].split(" --\x3e ")[1]);var g=e[2];if(2<e.length)for(f=3;f<e.length;f++)g+="\n"+e[f];ka[d]={};ka[d].start=MVPUtils.toSeconds(qa);ka[d].end=MVPUtils.toSeconds(h);ka[d].text=g}d++}}Pb[a.label]=ka;Va=!0}).fail(function(a,b,c){console.log(a,b,
c)})}function t(a){a.preventDefault();if(!l)return!1;a=b(a.currentTarget);a.hasClass("mvp-playback-toggle")||a.hasClass("mvp-big-play")?n.togglePlayback():a.hasClass("mvp-playlist-toggle")?Kc():a.hasClass("mvp-info-toggle")?Sa():a.hasClass("mvp-info-close")?Sa(!1):a.hasClass("mvp-share-close")?xa(!1):a.hasClass("mvp-prev-toggle")?jc():a.hasClass("mvp-next-toggle")?Qb():a.hasClass("mvp-seek-backward")?n.seekBackward():a.hasClass("mvp-seek-forward")?n.seekForward():a.hasClass("mvp-share-toggle")?xa():
a.hasClass("mvp-share-item")&&I(a.attr("data-type").toLowerCase())}function Ea(a){a.preventDefault();if(!l)return!1;a=b(a.currentTarget);if(E&&E.is(a))return!1;kc=!0;y.processPlaylistRequest(a.index());b(n).trigger("clickPlaylistItem",{instance:n,instanceName:J})}function O(a){a.preventDefault();if(!l)return!1;a=b(a.currentTarget);if(E&&E.is(a))return!1;a.addClass("mvp-playlist-item-selected")}function ha(a){a.preventDefault();if(!l)return!1;a=b(a.currentTarget);if(E&&E.is(a))return!1;a.removeClass("mvp-playlist-item-selected")}
function ia(){E.removeClass("mvp-playlist-item-selected");b(n).trigger("playlistItemEnabled",{instance:n,instanceName:J});E=null}function Qa(a){a.preventDefault();if(!l||!h)return!1;P()}function Ra(a){a.preventDefault();if(!l||!h)return!1;ya()}function P(){k&&ba&&(lc.removeClass("mvp-player-controls-hidden"),"image"==h&&"image_360"!=G&&mc.show(),K&&K.addClass("mvp-subtitle-bottom"),Rb=!1,N&&(C&&clearTimeout(C),C=setTimeout(function(){clearTimeout(this);C=null;ya()},5E3)))}function ya(){!S||N&&(Ia&&
"video_360"==G||"image_360"==G||"youtube"==h)||(lc.addClass("mvp-player-controls-hidden"),mc.hide(),K&&K.removeClass("mvp-subtitle-bottom"),A.hide(),tb.hide().removeClass("mvp-menu-bottom"),Sb.hide().removeClass("mvp-menu-bottom"),ub.hide().removeClass("mvp-menu-bottom"),x.removeClass("mvp-holder-visible"),e.removeClass("mvp-holder-visible"),V.css("display","none"),Rb=!0,N&&(C&&clearTimeout(C),C=setTimeout(function(){clearTimeout(this);C=null;ya()},5E3)))}function Fa(a){C&&clearTimeout(C);a&&(Lc!=
a.clientX&&(P(),document.body.style.cursor="default"),Lc=a.clientX);C=setTimeout(function(){clearTimeout(this);C=null;S&&(ya(),document.body.style.cursor="none")},5E3)}function Sa(a){if("undefined"!==typeof a){if(Ja&&1==a||!Ja&&0==a)return!1;Ja=!a}Ka&&xa(!1);Ja?(nc.hide(),Wa&&(n.playMedia(),Wa=!1)):(S&&(n.pauseMedia(),Wa=!0),nc.show());Ja=!Ja}function xa(a){if("undefined"!==typeof a){if(Ka&&1==a||!Ka&&0==a)return!1;Ka=!a}Ja&&Sa(!1);Ka?(oc.hide(),Wa&&(n.playMedia(),Wa=!1)):(S&&(n.pauseMedia(),Wa=!0),
oc.show());Ka=!Ka}function rb(a){vb=!0;sa.show();Tb?Mc():R.empty();var c=b(a);if(0==c.length)return alert("Failed playlist selection! Playlist - "+a+" does not exist. Check activePlaylist option in settings!"),Jc(),!1;pc=a;b(n).trigger("playlistStartLoad",{instance:n,instanceName:J});Ub=-1;Xa=[];ca=[];if(void 0!=c.attr("data-type")&&"xml"==c.attr("data-type"))oa(Vb(c));else{var d,f,e;c.children(".mvp-playlist-item").each(function(){f=b(this);e=f.attr("data-type");RegExp(/^image/).test(e)?ca.push(f.clone()):
RegExp(/^video/).test(e)?ca.push(f.clone()):void 0!=f.attr("data-noapi")?ca.push(f.clone()):(d=Vb(f),ca.push(d))});L=ca.length;aa()}}function aa(){Ub++;if(Ub>L-1)gd();else{var a=ca[Ub],d=a.type;d?RegExp(/^youtube/).test(d)?(Wb||(Wb=new MVPYoutubeLoader(c),b(Wb).on("MVPYoutubeLoader.END_LOAD",function(a,b){var c,d=b.length;for(c=0;c<d;c++){var f=b[c];Xa.push(f)}aa()})),Wb.setData(a)):RegExp(/^folder/).test(d)&&qb(a):(Xa.push(a),aa())}}function qb(a){if("file:"==window.location.protocol)return console.log("Reading files from folders locally is not possible! This requires online server connection."),
aa(),!1;var c=a.type;if("folder_video"==c)var d=["mp4"];else"folder_image"==c&&(d=["jpg","jpeg","png","gif"]);b.ajax({type:"GET",url:ld+"includes/folder_parser.php",data:{type:d,dir:a.path,limit:a.limit||100},dataType:"json"}).done(function(d){MVPUtils.keysrt(d,"filename");var f,e=d.length;for(f=0;f<e;f++){var h=d[f];if("folder_video"==c){if(/.mp4/.test(h.basename)){var g=b.extend(!0,{},a);g.type="video";g.origtype="folder_video";var ra=h.fullpath;g.mp4=ra;g.poster=ra.substr(0,ra.lastIndexOf("/")+
1)+"poster/"+h.filename+".jpg";g.thumb||(g.thumb=g.poster.replace(/\/main\/(?!.*\/poster\/)/,"/thumb/"));g.share||(g.share=ra);g.title||(g.title=h.filename);Xa.push(g)}}else"folder_image"==c&&/.jpg|jpeg|png|gif/.test(h.basename)&&(g=b.extend(!0,{},a),g.type="image",g.origtype="folder_image",ra=h.fullpath,g.image=ra,g.thumb||(g.thumb=ra.substr(0,ra.lastIndexOf("/")+1)+"thumb/"+h.filename+".jpg"),g.share||(g.share=ra),g.title||(g.title=h.filename),Xa.push(g))}aa()}).fail(function(a,b,c){console.log(a,
b,c);aa()})}function oa(a){b.ajax({type:"GET",url:a.path,dataType:"html"}).done(function(a){var c,d,f;b(a).children(".mvp-playlist-item").each(function(){c=b(this);d=c.attr("data-type");RegExp(/^image/).test(d)?ca.push(c):RegExp(/^video/).test(d)?ca.push(c):void 0!=c.attr("data-noapi")?ca.push(c):(f=Vb(c),ca.push(f))});L=ca.length;aa()}).fail(function(a,b,c){console.log(a,b,c);aa()})}function gd(){var a,c=Xa.length,d,f=0;for(a=0;a<c;a++){gb&&f++;var e=Xa[a];console.log(e);var g=e.type;if(wb){if(e instanceof
b&&e.hasClass("mvp-playlist-item"))if(g=e,gb){h?h.after(g):qc?g.appendTo(R):R.children("div").eq(xb).before(g);var h=g}else g.appendTo(R);else{e.origclasses||(e.origclasses="mvp-playlist-item");g=b('<div class="'+e.origclasses+'"/>').attr({"data-type":g});delete e.origclasses;gb?(h?h.after(g):qc?g.appendTo(R):R.children("div").eq(xb).before(g),h=g):g.appendTo(R);if(d=e.thumb||e.thumbDefault){var k=b("<div/>").addClass("mvp-playlist-thumb").appendTo(g);b(new Image).addClass("mvp-thumbimg mvp-hidden").appendTo(k).on("load",
function(){b(this).removeClass("mvp-hidden").addClass("mvp-visible")}).attr("src",d)}if(e.title||e.description)d=b('<div class="mvp-playlist-info"></div>').appendTo(g),e.title&&b('<span class="mvp-playlist-title">'+e.title+"</span>").appendTo(d),e.description&&b('<span class="mvp-playlist-description">'+e.description+"</span>").appendTo(d);e.id&&g.attr({"data-path":e.id});e.mp4&&g.attr({"data-mp4":e.mp4});e.image&&g.attr({"data-image":e.image});e.poster&&g.attr({"data-poster":e.poster});e.download&&
g.attr({"data-download":e.download});e.share&&g.attr({"data-share":e.share})}g.on("click",Ea);if(!N)g.on("mouseenter",O).on("mouseleave",ha)}}Tb=R;L=R.children(".mvp-playlist-item").length;gb?(a=y.getCounter(),y.setPlaylistItems(L,!1),xb<=a&&(qc||y.reSetCounter(a+f)),Nc?(Nc=!1,Oc&&!N&&setAutoPlay(!0),y.setCounter(xb,!1)):Oc&&y.setCounter(xb,!1),-1!=y.getCounter()&&y.getCounter()):y.setPlaylistItems(L);Jc();b(n).trigger("playlistEndLoad",{instance:n,instanceName:J})}function Ic(){yb.mCustomScrollbar({axis:"horizontal"==
rc?"x":"y",theme:c.playlistScrollTheme,scrollInertia:0,scrollButtons:{enable:!0},mouseWheel:{normalizeDelta:!0,deltaFactor:50,preventDefault:!0},keyboard:{enable:!1},advanced:{autoExpandHorizontalScroll:!0},callbacks:{onOverflowYNone:function(){yb.find(".mCSB_container").addClass("mvp-mCSB_full")},onOverflowY:function(){yb.find(".mCSB_container").removeClass("mvp-mCSB_full")}}});zb=!0}function Jc(){sa.hide();vb=!1;l||(l=!0,wb&&!zb&&Pc&&(Ic(),zb=!0),x.on("mouseenter",Qa).on("mouseleave",Ra),Ab(),r(u),
b(n).trigger("setupDone",{instance:n,instanceName:J}));if(wb){var a=[];R.find(".mvp-thumbimg").each(function(){a.push(b(this))});var d=0,e;for(e=0;e<L;e++)setTimeout(function(){clearTimeout(this);a[d].addClass("mvp-visible");d++},50+50*e);c.truncatePlaylistDescription&&R.find(".mvp-playlist-info").each(function(){b(this).dotdotdot()})}!sc&&!gb&&0<L&&(e=c.activeItem,e>L-1&&(e=L-1),-1<e&&y.setCounter(e,!1),sc=!0);gb=!1}function hd(){R.find(".mvp-playlist-item").each(function(){var a=b(this).on("click",
Ea);if(!N)a.on("mouseenter",O).on("mouseleave",ha)});L=R.children(".mvp-playlist-item").length;Tb=R;var a=[];R.find(".mvp-thumbimg").each(function(){a.push(b(this))});var d=0,e=a.length,f;for(f=0;f<e;f++)setTimeout(function(){clearTimeout(this);a[d].addClass("mvp-visible");d++},50+50*f);l||(l=!0,wb&&!zb&&Pc&&(Ic(),zb=!0),x.on("mouseenter",Qa).on("mouseleave",Ra),Ab(),r(u),b(n).trigger("setupDone",{instance:n,instanceName:J}));sa.hide();vb=!1;b(n).trigger("playlistEndLoad",{instance:n,instanceName:J});
e=c.activeItem;e>L-1&&(e=L-1);y.setPlaylistItems(L);-1<e&&y.setCounter(e,!1)}function id(){if(Bb&&void 0!=k.hls){if("file:"==window.location.protocol)return alert("Playing HLS requires server connection!"),!1;h="video";G="hls";La=k.hls}else if("video"==h||"image"==h){k.quality||(k.quality=Kb);var a,b=k.path.length;for(a=0;a<b;a++){var c=k.path[a];if(k.quality==c.quality){La=c.path;break}}}}function sb(a){Cb=a;if(h)if(Cb){Ya=!1;U&&cancelAnimationFrame(U);if("video"==h){hb=0;"video"==h&&g&&(hb=g.currentTime);
Bb&&"hls"==G&&Ba.detachMedia();if(g){g.pause();try{g.currentTime=0}catch(fb){}g.src=""}g=null;T&&T.off("ended loadedmetadata waiting playing play pause error seeked")}else"image"==h&&("image_360"==G?(Za&&Za.hide(),ib&&ib.reset(),Db=!1):(jb.hide().find(".mvp-media").remove(),da=null));Ma.hide();ba=S=!1}else tc();if(!Cb){k=Vb(E);"youtube_single"==k.type&&(k.type="youtube");h=k.type;"video_360"==h?(h="video",G="video_360"):"image_360"==h&&(h="image",G="image_360");if("video"==h){if(k.poster&&void 0==
E.attr("data-poster-shown")){b(new Image).addClass("mvp-media").appendTo(Na.show()).on("load",function(){ea=b(this);MVPAspectRatio.resizeMedia("image",ta,x,ea);ea.addClass("mvp-visible");Ma.show()}).on("error",function(a){console.log(a)}).attr("src",k.poster);return}E.removeAttr("data-poster-shown")}k.subtitles&&Gb()}if("video"==h||"image"==h)id(),Cb||(a=D(),Qc&&1==a.length||"hls"!=G&&B(a,k.quality));if("video"==h){uc?(Na.show(),T=Na.find(".mvp-media"),g=T[0]):(a='<video muted="muted" autoplay="autoplay" class="mvp-media" preload="auto" playsinline>'+
('<source src="'+La+'" />'),a+="</video>",Na.show().html(a),T=Na.find(".mvp-media"),g=T[0],N&&c.forceMobileAutoplay&&r(0));if(Ia&&"video_360"==G&&("file:"==window.location.protocol&&console.log("Playing 360 video and images requires online server connection!"),!Rc)){Oa=new THREE.WebGLRenderer({antialias:!0});Oa.setSize(640,360);Oa.domElement.className+="mvp-canvas-video";W.prepend(b(Oa.domElement));Xb=W.find(".mvp-canvas-video");kb=new THREE.Texture(g);kb.minFilter=THREE.LinearFilter;kb.magFilter=
THREE.LinearFilter;kb.format=THREE.RGBFormat;Yb=new THREE.Scene;a=new THREE.SphereGeometry(500,60,40);a.scale(-1,1,1);var d=new THREE.MeshBasicMaterial({map:kb});a=new THREE.Mesh(a,d);Yb.add(a);ua=new THREE.PerspectiveCamera(90,640/360,.1,1E4);Yb.add(ua);ua.position.x+=.1;Eb=new THREE.OrbitControls(ua);Eb.addEventListener("change",Sc);Eb.enableZoom=!1;Rc=!0}r(u);T.on("ended",function(){vc()}).on("loadedmetadata",function(){MVPAspectRatio.resizeMedia("video",ta,x,T);T.addClass("mvp-visible");k.playbackRate?
g.playbackRate=Number(k.playbackRate):v(1);hb&&(g.currentTime=hb);hb=null;k.poster||$a?(g.play(),P()):Ma.show();T.find("source").remove();Tc&&($a=!0)}).on("waiting",function(){sa.show()}).on("playing",function(){sa.hide()}).on("play",function(){Uc()}).on("pause",function(){Vc();sa.hide()}).on("seeking",function(){Ya=!1}).on("seeked",function(){sa.hide();Ia&&"video_360"==G&&(Ya=!0,requestAnimationFrame(wc))}).on("ratechange",function(){v(g.playbackRate)}).on("error",function(a){switch(a.target.error.code){case a.target.error.MEDIA_ERR_ABORTED:console.log("You aborted the video playback.");
break;case a.target.error.MEDIA_ERR_NETWORK:console.log("A network error caused the video download to fail part-way.");break;case a.target.error.MEDIA_ERR_DECODE:console.log("The video playback was aborted due to a corruption problem or because the video used features your browser did not support.");break;case a.target.error.MEDIA_ERR_SRC_NOT_SUPPORTED:console.log("The video could not be loaded, either because the server or network failed or because the format is not supported.");break;default:console.log("An unknown error occurred.")}});
Bb&&"hls"==G?Ba.attachMedia(g):(g.src=La,g.load());md&&!uc&&g.play();uc=!0}else if("image"==h)"image_360"==G?("file:"==window.location.protocol&&console.log("Playing 360 video and images requires online server connection!"),Wc?Zb.load(La,function(a){Za.show();$b.map=a;a=W.width();var b=W.height();va.setSize(a,b);wa.aspect=a/b;wa.updateProjectionMatrix();U&&cancelAnimationFrame(U);U=requestAnimationFrame(xc);S=ba=!0;lb.show();mb=!0;P();Db=!0}):(wa=new THREE.PerspectiveCamera(75,640/360,1,1100),wa.position.x=
1,yc=new THREE.Scene,a=new THREE.SphereBufferGeometry(500,60,40),a.scale(-1,1,1),Zb=new THREE.TextureLoader,$b=new THREE.MeshBasicMaterial({map:Zb}),Zb.load(La,function(a){Za.show();$b.map=a;a=W.width();var b=W.height();va.setSize(a,b);wa.aspect=a/b;wa.updateProjectionMatrix();U&&cancelAnimationFrame(U);U=requestAnimationFrame(xc);S=ba=!0;lb.show();mb=!0;P();Db=!0},function(a){},function(a){}),Xc=new THREE.Mesh(a,$b),yc.add(Xc),va=new THREE.WebGLRenderer,va.setPixelRatio(window.devicePixelRatio),
va.setSize(640,360),va.domElement.className+="mvp-canvas-image",W.prepend(b(va.domElement)),Za=W.find(".mvp-canvas-image"),ib=new THREE.OrbitControls(wa),ib.addEventListener("change",Sc),Wc=!0)):(sa.show(),b(new Image).addClass("mvp-media").prependTo(jb.show()).on("load",function(){sa.hide();da=b(this);zc=da.width();Ac=da.height();MVPAspectRatio.resizeMedia("image",ta,x,da);da.addClass("mvp-visible");S=ba=!0;P()}).on("error",function(a){console.log(a)}).attr("src",La));else if("youtube"==h){var e=
function(a){switch(a.data){case 2:console.log("Error code = "+a.data+": The request contains an invalid parameter value. For example, this error occurs if you specify a video ID that does not have 11 characters, or if the video ID contains invalid characters, such as exclamation points or asterisks.");break;case 100:console.log("Error code = "+a.data+": Video not found, removed, or marked as private");break;case 101:console.log("Error code = "+a.data+": Embedding disabled for this video");break;case 150:console.log("Error code = "+
a.data+": Video not found, removed, or marked as private [same as error 100]")}},f=function(a){nb.hasClass("mvp-force-hidden")||-1==a.data||(0==a.data?vc():1==a.data?(Bc||(k.quality&&p.setPlaybackQuality(k.quality),a=p.getAvailableQualityLevels(),Qc&&1==a.length||B(a,p.getPlaybackQuality()),k.playbackRate&&1!=k.playbackRate?p.setPlaybackRate(Number(k.playbackRate)):v(1),Bc=!0,Tc&&($a=!0)),Uc()):2==a.data&&Vc())},l=function(a){v(a.data)},m=function(a){H(a.data)},q=function(a){Yc=!0;N&&c.forceMobileAutoplay&&
(u=0,r());p.setVolume(100*u);$a&&p.playVideo()};if(Zc)Yc&&($a?p.loadVideoById({videoId:k.path,startSeconds:k.start,endSeconds:k.end,suggestedQuality:k.quality}):p.cueVideoById({videoId:k.path,startSeconds:k.start,endSeconds:k.end,suggestedQuality:k.quality}));else{var t="ytplayer"+Math.floor(16777215*Math.random());a=("https:"==window.location.protocol?"https:":"http:")+"//www.youtube.com/embed/"+k.path+"?controls=0&amp;rel=0&amp;showinfo=0&amp;enablejsapi=1&amp;playsinline=1&amp;theme=dark&amp;modestbranding=0&amp;wmode=transparent";
k.start&&(a+="&amp;start="+k.start);k.end&&(a+="&amp;end="+k.end);Ca=b("<iframe/>",{id:t,frameborder:0,src:a,webkitAllowFullScreen:!0,mozallowfullscreen:!0,allowFullScreen:!0}).addClass("mvp-iframe").css("display","block");nb.show().append(Ca);a=document.createElement("script");a.src="https://www.youtube.com/iframe_api";d=document.getElementsByTagName("script")[0];d.parentNode.insertBefore(a,d);Zc=!0}window.onYouTubeIframeAPIReady=function(){p=new YT.Player(t,{events:{onReady:q,onPlaybackQualityChange:m,
onPlaybackRateChange:l,onStateChange:f,onError:e}})};nb.removeClass("mvp-force-hidden");k.width&&k.height&&(Ca.sw=k.width,Ca.sh=k.height,MVPAspectRatio.resizeMedia("youtube",ta,nb,Ca))}if(!Cb){if("video"==h||"youtube"==h)za.show(),ab.show(),ac.show(),bc.show();k.description?(Cc.html(k.description),cc.show()):E.find(".mvp-playlist-description").length&&(Cc.html(E.find(".mvp-playlist-description").html()),cc.show());nd&&k.download?$c.show().find("a").attr("href",k.download).attr("download",""):$c.hide();
N||(a=x.offset().top,Ga.scrollTop()>a&&b("html,body").animate({scrollTop:a},500))}b(n).trigger("mediaRequest",{instance:n,instanceName:J,counter:Aa})}function Sc(){mb&&setTimeout(function(){clearTimeout(this);lb.hide();mb=!1},1E3)}function tc(){Ya=!1;U&&cancelAnimationFrame(U);lb.hide();mb=!1;if("video"==h){Bb&&"hls"==G&&Ba.detachMedia();Ia&&"video_360"==G&&(Xb&&Xb.hide(),Eb&&Eb.reset());if(g){g.pause();try{g.currentTime=0}catch(a){}g.src="";g=null}T&&T.off("ended loadedmetadata waiting playing play pause error seeked");
Na.hide()}else"image"==h?"image_360"==G?(Za&&Za.hide(),ib&&ib.reset(),Db=!1):(jb.hide().find(".mvp-media").remove(),da=null):"youtube"==h&&p&&(nb.addClass("mvp-force-hidden"),p.stopVideo(),Bc=!1,Ca&&(Ca.sw=null,Ca.sh=null));ea&&(ea.remove(),ea=null);za.hide();ab.hide();ac.hide();bc.hide();Mb.hide();Lb.empty();Va=!1;ka=[];Pb=[];Fb.empty();Q=K=null;Ua.empty();Ob.hide();lc.addClass("mvp-player-controls-hidden");mc.hide();K&&K.removeClass("mvp-subtitle-bottom");A.hide();tb.hide().removeClass("mvp-menu-bottom");
ub.hide().removeClass("mvp-menu-bottom");x.removeClass("mvp-holder-visible");e.removeClass("mvp-holder-visible");V.css("display","none");Wa=!1;nc.hide();Cc.empty();cc.hide();Ja=!1;oc.hide();Ka=!1;Ma.hide();k=G=h=hb=null;ba=S=!1}function ad(){ea.on("transitionend",function(){b(this).remove();ea=null}).remove("mvp-visible").addClass("mvp-hidden")}function Mc(){h&&tc();R.empty();L=0;y.reSetCounter();sc=!1;pc=""}function Qb(){l&&0!=L&&y.advanceHandler(1,!0)}function jc(){l&&0!=L&&y.advanceHandler(-1,
!0)}function Uc(){sa.hide();Ma.hide();ab.find(".mvp-play").hide();ab.find(".mvp-pause").show();if(!ba){ja=Ib.width();if(Ia&&"video_360"==G){Na.hide();Xb.show();lb.show();mb=!0;var a=W.width(),c=W.height();Oa.setSize(a,c);ua.aspect=a/c;ua.updateProjectionMatrix();Ya=!0}U&&cancelAnimationFrame(U);U=requestAnimationFrame(wc);b(n).trigger("mediaStart",{instance:n,instanceName:J,counter:y.getCounter()});ba=!0;P()}if(1<mvp_mediaArr.length)for(c=mvp_mediaArr.length,a=0;a<c;a++)n!=mvp_mediaArr[a].inst&&mvp_mediaArr[a].inst.pauseMedia();
N&&(C||(C=setTimeout(function(){clearTimeout(this);C=null;ya()},5E3)));b(n).trigger("mediaPlay",{instance:n,instanceName:J,counter:y.getCounter()});S=!0}function Vc(){ab.find(".mvp-play").show();ab.find(".mvp-pause").hide();ba?Ma.show():"video"==h&&Ma.show();b(n).trigger("mediaPause",{instance:n,instanceName:J,counter:y.getCounter()});S=!1}function xc(){va.render(yc,wa);U=requestAnimationFrame(xc)}function wc(){if(Ia&&"video_360"==G){if(!Ya)return;T.readyState===T.HAVE_ENOUGH_DATA&&(kb.needsUpdate=
!0);Oa.render(Yb,ua)}if("video"==h){var a=g.currentTime,c=g.duration;if("undefined"!==typeof g.buffered&&0!=g.buffered.length){try{var d=g.buffered.end(g.buffered.length-1)}catch(Bd){}isNaN(d)||(d/=Math.floor(g.duration),bd.width(d*ja))}}else"youtube"==h&&(a=p.getCurrentTime(),c=p.getDuration(),d=p.getVideoLoadedFraction(),bd.width(d*ja));if(MVPUtils.isNumber(a)&&MVPUtils.isNumber(c)&&(od.width(a/c*ja),k.end&&a>=k.end&&vc(),Va&&ka.length))for(d=ka.length,c=0;c<d;c++){var e=ka[c];var f=e.start;var l=
e.end;e=e.text;a>=f&&a<=l?K||(K=b('<p class="mvp-subtitle">'+e+"</p>"),Rb||K.addClass("mvp-subtitle-bottom"),K.start=f,K.end=l,Fb.append(K)):K&&(a<K.start||a>K.end)&&(K.remove(),K=null)}U=requestAnimationFrame(wc)}function vc(){b(n).trigger("mediaEnd",{instance:n,instanceName:J,counter:y.getCounter()});var a=k.start||0;"next"==Dc?Qb():"loop"==Dc?"video"==h?g&&(g.currentTime=a,g.play()):"youtube"==h&&p&&(p.seekTo(a),p.playVideo()):"rewind"==Dc&&("video"==h?g&&(g.currentTime=a,g.pause()):"youtube"==
h&&p&&(p.seekTo(a),p.pauseVideo()))}function Ab(){if("right_bottom"==Ec)if(675<e.width())if(e.removeClass("mvp-wrapper-bottom"),x.removeClass("mvp-player-holder-bottom"),fa.removeClass("mvp-playlist-holder-bottom"),e.css("height","auto"),x.css("height","100%"),"horizontal"==rc){var a=X?e.height()-fa.height():e.height();x.height(a)}else a=X?e.width()-fa.width():e.width(),x.width(a);else{e.addClass("mvp-wrapper-bottom");x.addClass("mvp-player-holder-bottom");fa.addClass("mvp-playlist-holder-bottom");
a=e.width();var b=a/(16/9);x.height(b);X?e.height(b+fa.height()):e.height(b);"fullscreen"==Pa&&(X?x.height(e.height()-fa.height()):x.height(e.height()))}else"right"==Ec?(a=X?e.width()-fa.width():e.width(),x.width(a)):"bottom"==Ec&&(a=X?e.height()-fa.height():e.height(),x.height(a));ja=Ib.width();h&&("video"==h?Ia&&"video_360"==G?Ya&&(a=W.width(),b=W.height(),Oa.setSize(a,b),ua.aspect=a/b,ua.updateProjectionMatrix()):ea?MVPAspectRatio.resizeMedia("image",ta,x,ea):T&&MVPAspectRatio.resizeMedia("video",
ta,x,T):"image"==h?"image_360"==G?Db&&(a=W.width(),b=W.height(),va.setSize(a,b),wa.aspect=a/b,wa.updateProjectionMatrix()):da&&(Fc?ob.resize():MVPAspectRatio.resizeMedia("image",ta,x,da)):"youtube"==h&&k.width&&k.height&&MVPAspectRatio.resizeMedia("youtube",ta,nb,Ca))}function Kc(a){if(!l)return!1;if("undefined"!==typeof a){if(X&&1==a||!X&&0==a)return!1;X=!a}X?fa.hide():fa.show();X=!X;Ab()}function Vb(a,c){var d={};d.origclasses=a.attr("class");d.type=a.attr("data-type");void 0!=a.attr("data-noapi")&&
(d.noapi=!0);void 0==a.attr("data-hls")||MVPUtils.isEmpty(a.attr("data-hls"))||(d.hls=a.attr("data-hls"));if("video"==d.type||"video_360"==d.type){var e=[];b.each(a[0].attributes,function(a,b){if(/mp4/.test(b.name)&&0==b.name.indexOf("data-mp4")){var c=b.name.substr(9).toLowerCase();MVPUtils.isEmpty(c)&&(c=Kb);e.push({quality:c,path:b.value})}});MVPUtils.keysrt(e,"quality");d.path=e}else"image"==d.type||"image_360"==d.type?(e=[],b.each(a[0].attributes,function(a,b){if(/image/.test(b.name)&&0==b.name.indexOf("data-image")){var c=
b.name.substr(11).toLowerCase();MVPUtils.isEmpty(c)&&(c=Kb);e.push({quality:c,path:b.value})}}),MVPUtils.keysrt(e,"quality"),d.path=e):void 0==a.attr("data-path")||MVPUtils.isEmpty(a.attr("data-path"))||(d.path=a.attr("data-path"));void 0==a.attr("data-quality")||MVPUtils.isEmpty(a.attr("data-quality"))||(d.quality=a.attr("data-quality"));void 0==a.attr("data-download")||MVPUtils.isEmpty(a.attr("data-download"))||(d.download=a.attr("data-download"));void 0==a.attr("data-poster")||MVPUtils.isEmpty(a.attr("data-poster"))||
(d.poster=a.attr("data-poster"));void 0!=a.attr("data-start")&&!MVPUtils.isEmpty(a.attr("data-start"))&&MVPUtils.isNumber(a.attr("data-start"))&&(d.start=Number(a.attr("data-start")));void 0!=a.attr("data-end")&&!MVPUtils.isEmpty(a.attr("data-end"))&&MVPUtils.isNumber(a.attr("data-end"))&&(d.end=Number(a.attr("data-end")));void 0!=a.attr("data-playback-rate")&&!MVPUtils.isEmpty(a.attr("data-playback-rate"))&&MVPUtils.isNumber(a.attr("data-playback-rate"))&&(d.playbackRate=Number(a.attr("data-playback-rate")));
void 0==a.attr("data-share")||MVPUtils.isEmpty(a.attr("data-share"))||(d.share=a.attr("data-share"));void 0==a.attr("data-limit")||MVPUtils.isEmpty(a.attr("data-limit"))||(d.limit=Number(a.attr("data-limit")));void 0==a.attr("data-width")||MVPUtils.isEmpty(a.attr("data-width"))||void 0==a.attr("data-height")||MVPUtils.isEmpty(a.attr("data-height"))||(d.width=parseInt(a.attr("data-width"),10),d.height=parseInt(a.attr("data-height"),10));if(a.children(".mvp-subtitles").length){var f=a.children(".mvp-subtitles");
f.children("div").length&&(d.subtitles=[],f.children("div").each(function(){var a=b(this),c={label:a.attr("data-label"),src:a.attr("data-src")};void 0!=a.attr("data-default")&&(c["default"]=!0);d.subtitles.push(c)}))}return d}var e=b(this),W=e.find(".mvp-media-holder").show();e.find(".mvp-playlist-list");var fa=e.find(".mvp-playlist-holder"),yb=e.find(".mvp-playlist-inner"),R=e.find(".mvp-playlist-content"),Fb=e.find(".mvp-elem-holder"),x=e.find(".mvp-player-holder").show(),Na=e.find(".mvp-video-holder"),
jb=e.find(".mvp-image-holder"),nb=e.find(".mvp-youtube-holder"),lc=e.find(".mvp-player-controls"),ab=e.find(".mvp-playback-toggle"),za=e.find(".mvp-seekbar"),Ib=e.find(".mvp-progress-bg"),bd=e.find(".mvp-load-level"),od=e.find(".mvp-progress-level"),bc=e.find(".mvp-volume-wrapper"),eb=e.find(".mvp-volume-toggle"),V=e.find(".mvp-volume-seekbar"),cb=e.find(".mvp-volume-bg"),kd=e.find(".mvp-volume-level"),nc=e.find(".mvp-info-holder"),cc=e.find(".mvp-info-toggle"),Cc=e.find(".mvp-info-data");e.find(".mvp-embed");
var pd=e.find(".mvp-playlist-toggle"),sa=e.find(".mvp-player-loader"),Ma=e.find(".mvp-big-play"),$c=e.find(".mvp-download-toggle"),qd=e.find(".mvp-share-toggle"),oc=e.find(".mvp-share-holder"),rd=e.find(".mvp-seek-backward"),sd=e.find(".mvp-seek-forward"),mc=e.find(".mvp-image-detail").on("click",function(){Fc=!0;pb.addClass("mvp-fs-overflow");e.addClass("mvp-fs");jb.addClass("mvp-fs");ob?ob.initMedia({image:da,fullImageWidth:zc,fullImageHeight:Ac}):ob=new MVPImageZoom({holder:jb,settings:c,image:da,
fullImageWidth:zc,fullImageHeight:Ac});cd.show();dd.show()}),lb=e.find(".mvp-vr-info"),J=c.instanceName,ld=c.sourcePath,rc=c.playlistScrollOrientation,Dc=c.mediaEndAction,td=c.useKeyboardNavigationForPlayback,u=c.volume,$a=c.autoPlay,X=c.playlistOpened,Pc=c.usePlaylistScroll,ta=c.aspectRatio,Tc=c.sequentialAutoplay,Qc=c.hideQualityMenuOnSingleQuality,Kb=c.defaultMenuQuality||"default",N=MVPUtils.isMobile();MVPUtils.isIOS();var md=MVPUtils.isAndroid(),ed=MVPUtils.hasFullscreen(),nd=MVPUtils.hasDownloadSupport(),
ud=MVPUtils.volumeCanBeSet(),vd=MVPUtils.supportsWebGL(),wd=MVPUtils.isChrome(),l=!1,vb=!0,Bb=window.Hls&&Hls.isSupported(),n=this;b("body");var Ga=b(window),Y=b(document),pb=b("html"),Gc,ba,U,k,pc,E,L,ea,g,T,uc,da,ob,Fc,zc,Ac,Wb,Ca,p,Zc,Yc,Bc,Ia=!0,mb,Rc,Xb,Oa,kb,Eb,ua,Yb,Ya,Wc,Db,Za,Zb,$b,wa,yc,va,Xc,ib,Cb,hb,h,G,La,S,kc,Wa,Ja,Ka,C,Lc=0,Rb=!0,Ec=c.playlistPosition,Tb,sc,Ub,Xa=[],ca=[],qc,xb,gb,Oc,Nc,zb,wb=fa.length;"undefined"===typeof window.mvp_mediaArr&&(window.mvp_mediaArr=[]);mvp_mediaArr.push({inst:n,
id:J});N&&(c.forceMobileAutoplay?($a=!0,u=0):$a=!1);ed||(ta=1);wb||(X=!1);X&&fa.show();vd||(Ia=!1,lb.remove(),wd&&alert("Turn Hardware Acceleration On Within Chrome Browser to enable 360 video and images!"));if("ontouchstart"in window){var dc="touchstart.ap mousedown.ap";var pa="touchmove.ap mousemove.ap";var bb="touchend.ap mouseup.ap"}else window.PointerEvent?(dc="pointerdown.ap",pa="pointermove.ap",bb="pointerup.ap"):(dc="mousedown.ap",pa="mousemove.ap",bb="mouseup.ap");Na.on("click",function(){N?
Rb?P():g&&(g.paused?g.play():g.pause()):g&&(g.paused?g.play():g.pause())});var Pa="normal",Hc;Y.on("fullscreenchange mozfullscreenchange MSFullscreenChange webkitfullscreenchange",function(a){Hc==J&&(C&&clearTimeout(C),"fullscreen"==Pa?(Pa="normal",pb.removeClass("mvp-fs-overflow"),e.removeClass("mvp-fs"),la.find(".mvp-fullscreen-exit").hide(),la.find(".mvp-fullscreen-enter").show(),N||Y.off("mousemove",Fa),P(),document.body.style.cursor="default",Hc=null,b(n).trigger("fullscreenExit",{instance:n,
instanceName:J})):(Pa="fullscreen",pb.addClass("mvp-fs-overflow"),e.addClass("mvp-fs"),la.find(".mvp-fullscreen-enter").hide(),la.find(".mvp-fullscreen-exit").show(),N?C=setTimeout(function(){clearTimeout(this);C=null;ya()},5E3):(Y.on("mousemove",Fa),C=setTimeout(function(){clearTimeout(this);C=null;Fa()},5E3)),b(n).trigger("fullscreenEnter",{instance:n,instanceName:J})))});var la=e.find(".mvp-fullscreen-toggle").on("click",function(a){Hc=J;a=e[0];ed?a.requestFullscreen?document.fullscreenElement?
document.exitFullscreen():a.requestFullscreen():a.webkitRequestFullScreen?document.webkitIsFullScreen?document.webkitCancelFullScreen():a.webkitRequestFullScreen():a.msRequestFullscreen?document.msIsFullscreen||document.msFullscreenElement?document.msExitFullscreen():a.msRequestFullscreen():a.mozRequestFullScreen&&(document.fullscreenElement||document.mozFullScreenElement?document.mozCancelFullScreen():a.mozRequestFullScreen()):("fullscreen"==Pa?(Pa="normal",pb.removeClass("mvp-fs-overflow"),e.removeClass("mvp-fs"),
document.body.style.cursor="default",la.find(".mvp-fullscreen-enter").hide(),la.find(".mvp-fullscreen-exit").show(),b(n).trigger("fullscreenExit",{instance:n,instanceName:J})):(Pa="fullscreen",pb.addClass("mvp-fs-overflow"),e.addClass("mvp-fs"),la.find(".mvp-fullscreen-enter").hide(),la.find(".mvp-fullscreen-exit").show(),N?C=setTimeout(function(){clearTimeout(this);C=null;ya()},5E3):(Y.on("mousemove",Fa),C=setTimeout(function(){clearTimeout(this);C=null;Fa()},5E3)),b(n).trigger("fullscreenEnter",
{instance:n,instanceName:J})),Ab())});if(c.disableRightClick)e.on("contextmenu",function(){return!1});var A=e.find(".mvp-tooltip");if(!N)e.find("[data-tooltip]").on("mouseenter",function(a){a=b(this);var c=e[0].getBoundingClientRect(),d=a[0].getBoundingClientRect();A.find("p").text(a.attr("data-tooltip"));if(void 0!=a.attr("data-tooltip-position")){if("left"==a.attr("data-tooltip-position"))var f=parseInt(d.top-c.top-A.outerHeight()/2+a.outerHeight()/2),g=parseInt(d.left-c.left-A.outerWidth())}else f=
parseInt(d.top-c.top-A.outerHeight()),g=parseInt(d.left-c.left-A.outerWidth()/2+a.outerWidth()/2);0>g?g=0:g+A.outerWidth()>e.width()&&(g=e.width()-A.outerWidth());0>f+c.top&&(f=parseInt(d.top-c.top+A.outerHeight()+15));A.css({left:g+"px",top:f+"px"}).show()}).on("mouseleave",function(a){A.hide()});var Hb,ja,jd=za.hasClass("mvp-position-top")?"top":"bottom";za.on(dc,function(a){q(a);return!1});if(!N){var ec=function(){ba&&(za.off(pa,w).off("mouseout",ec),Y.off("mouseout",ec),A.hide())};za.on("mouseover",
function(){ba&&(za.on(pa,w).on("mouseout",ec),Y.on("mouseout",ec))})}var Ta=V.hasClass("mvp-horizontal"),gc=.5;Ta?V.width():V.height();var db=Ta?cb.width():cb.height(),Jb;0>u?u=0:1<u&&(u=1);0!=u&&(gc=u);if(!ud)V.remove(),eb.on("click",function(a){m()});else if(!N)eb.on("click",function(a){m()});bc.on("mouseenter",function(){V.css("display","block")}).on("mouseleave",function(){V.css("display","none")});V.on(dc,function(a){F(a);return!1});if(!N){var fc=function(){V.off(pa,d).off("mouseout",fc);Y.off("mouseout",
fc);A.hide()};V.on("mouseover",function(){V.on(pa,d).on("mouseout",fc);Y.on("mouseout",fc)})}MVPUtils.isEmpty(c.facebookAppId)?console.log("facebookAppId has not been set in settings!"):ma(c.facebookAppId);var ac=e.find(".mvp-playback-rate-toggle"),ub=e.find(".mvp-playback-rate-holder"),ic=e.find(".mvp-playback-rate-menu"),hc;ac.on("mouseenter",function(){ub.show();ic.height()>ac.offset().top-Ga.scrollTop()&&(ub.addClass("mvp-menu-bottom"),x.addClass("mvp-holder-visible"),e.addClass("mvp-holder-visible"))}).on("mouseleave",
function(){ub.hide().removeClass("mvp-menu-bottom");x.removeClass("mvp-holder-visible");e.removeClass("mvp-holder-visible")});ic.find(".mvp-menu-item").each(function(){b(this).attr("data-label",b(this).find("a").text()).on("click",M)});var Mb=e.find(".mvp-quality-toggle").hide(),Sb=e.find(".mvp-quality-holder"),Lb=e.find(".mvp-quality-menu"),Ha;Mb.on("mouseenter",function(){Sb.show();Lb.height()>Mb.offset().top-Ga.scrollTop()&&(Sb.addClass("mvp-menu-bottom"),x.addClass("mvp-holder-visible"),e.addClass("mvp-holder-visible"))}).on("mouseleave",
function(){Sb.hide().removeClass("mvp-menu-bottom");x.removeClass("mvp-holder-visible");e.removeClass("mvp-holder-visible")});var Ob=e.find(".mvp-subtitle-toggle").hide(),tb=e.find(".mvp-subtitle-holder"),Ua=e.find(".mvp-subtitle-menu"),Q,Va,Nb="Off",Pb=[],ka=[],K;Ob.on("mouseenter",function(){tb.show();Ua.height()>Ob.offset().top-Ga.scrollTop()&&(tb.addClass("mvp-menu-bottom"),x.addClass("mvp-holder-visible"),e.addClass("mvp-holder-visible"))}).on("mouseleave",function(){tb.hide().removeClass("mvp-menu-bottom");
x.removeClass("mvp-holder-visible");e.removeClass("mvp-holder-visible")});this.setSubtitle=function(a){if(!l||!h)return!1;if(a==Nb||""==a)Va=!1,Fb.empty(),K=null,Q&&Q.removeClass("mvp-menu-active"),Q=Ua.find(".mvp-menu-item[data-label='"+Nb+"']").addClass("mvp-menu-active");else if(Pb[a])Va=!1,Fb.empty(),K=null,Q&&Q.removeClass("mvp-menu-active"),Q=Ua.find(".mvp-menu-item[data-label='"+a+"']").addClass("mvp-menu-active"),ka=Pb[a],Va=!0;else{var b,c=k.subtitles.length;for(b=0;b<c;b++){var d=k.subtitles[b];
if(d.label==a){Va=!1;Fb.empty();K=null;Q&&Q.removeClass("mvp-menu-active");Q=Ua.find(".mvp-menu-item[data-label='"+a+"']").addClass("mvp-menu-active");Da(d);break}}}};td&&Y.keyup(function(a){a.stopImmediatePropagation();a.preventDefault();if(!l)return!1;var c=a.keyCode;b(a.target);37==c?n.seekBackward():39==c?n.seekForward():33==c?jc():34==c?Qb():32==c?n.togglePlayback():77==c&&m()});var fd=[ab,pd,la,Ma,bc,cc,qd,rd,sd,e.find(".mvp-info-close"),e.find(".mvp-share-close"),e.find(".mvp-next-toggle"),
e.find(".mvp-prev-toggle"),e.find(".mvp-share-item")],xd=fd.length,Aa;for(Aa=0;Aa<xd;Aa++)b(fd[Aa]).css("cursor","pointer").on("click",t);var yd=e.find(".mvp-link-code").text(window.location.href);e.find(".mvp-link-copy").on("click",function(){MVPUtils.selectText(yd[0]);try{document.execCommand("copy")}catch(a){alert("Please press Ctrl/Cmd+C to copy code!")}});if(c.embedWidth&&!MVPUtils.isEmpty(c.embedWidth)&&c.embedHeight&&!MVPUtils.isEmpty(c.embedHeight)){var zd=c.embedSrc||window.location.href,
Ad=e.find(".mvp-embed-code").text('<iframe width="'+c.embedWidth+'" height="'+c.embedHeight+'" src="'+zd+'" frameborder="0" scrolling="no" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>');e.find(".mvp-embed-copy").on("click",function(){MVPUtils.selectText(Ad[0]);try{document.execCommand("copy")}catch(a){alert("Please press Ctrl/Cmd+C to copy code!")}})}var y=new MVPPlaylistManager(c);b(y).on("MVPPlaylistManager.COUNTER_READY",function(a,c){E&&ia();var d=y.getCounter();E=R.children(".mvp-playlist-item").eq(d);
E.length&&(E.addClass("mvp-playlist-item-selected"),0<L&&(kc||("horizontal"==rc?yb.mCustomScrollbar("scrollTo",parseInt(E.position().left),{scrollInertia:500}):yb.mCustomScrollbar("scrollTo",parseInt(E.position().top),{scrollInertia:500})),kc=!1),b(n).trigger("playlistItemDisabled",{instance:n,instanceName:J}));sb()});if(Bb){var Ba=new Hls;Ba.on(Hls.Events.MEDIA_ATTACHED,function(){Ba.loadSource(La)});Ba.on(Hls.Events.ERROR,function(a,b){if(b.fatal)switch(b.type){case Hls.ErrorTypes.NETWORK_ERROR:console.log("fatal network error encountered, try to recover");
Ba.startLoad();break;case Hls.ErrorTypes.MEDIA_ERROR:console.log("fatal media error encountered, try to recover");Ba.recoverMediaError();break;default:Ba.destroy()}})}var cd=b(".mvp-image-zoom").on("click",function(a){ob.zoomCustom()}),dd=b(".mvp-image-close").on("click",function(a){"fullscreen"==Pa&&la.click();pb.removeClass("mvp-fs-overflow");e.removeClass("mvp-fs");jb.removeClass("mvp-fs");cd.hide();dd.hide();ob.deactivate();MVPAspectRatio.resizeMedia("image",ta,x,da);Fc=!1});Ga.on("resize",function(){if(!l)return!1;
Gc&&clearTimeout(Gc);Gc=setTimeout(Ab,100)});this.playMedia=function(){if(!l||!h||S)return!1;"video"==h?ea?(ad(),E.attr("data-poster-shown",""),sb()):g&&g.play():"youtube"==h&&p.playVideo();S=!0};this.pauseMedia=function(){if(!l||!h||!S)return!1;"video"==h?g&&g.pause():"youtube"==h&&p.pauseVideo();S=!1};this.togglePlayback=function(){if(!l||!h)return!1;if("video"==h)ea&&!ba?(ad(),E.attr("data-poster-shown",""),sb()):g&&(g.paused?g.play():g.pause());else if("youtube"==h){var a=p.getPlayerState();1==
a?p.pauseVideo():2==a?p.playVideo():(-1==a||5==a||0==a)&&p.playVideo()}};this.nextMedia=function(){if(!l)return!1;Qb()};this.previousMedia=function(){if(!l)return!1;jc()};this.setVolume=function(a){if(!l)return!1;0>a?a=0:1<a&&(a=1);r(a)};this.toggleMute=function(){if(!l)return!1;m()};this.seek=function(a){if(!l||!h)return!1;"video"==h?g.currentTime=a:"youtube"==h&&p.seekTo(a)};this.seekBackward=function(a){if(!l||!h)return!1;if("video"==h){if(g)try{g.currentTime=Math.max(g.currentTime-(a||10),0)}catch(qa){console.log(qa)}}else"youtube"==
h&&(a=Math.max(p.getCurrentTime()-(a||10),0),p.seekTo(a))};this.seekForward=function(a){if(!l||!h)return!1;if("video"==h){if(g)try{g.currentTime=Math.min(g.currentTime+(a||10),g.duration)}catch(qa){console.log(qa)}}else"youtube"==h&&(a=Math.min(p.getCurrentTime()+(a||10),p.getDuration()),p.seekTo(a))};this.getCurrentTime=function(){if(!l||!h)return!1;if("video"==h)return g.currentTime;if("youtube"==h)return p.getCurrentTime()};this.getDuration=function(){if(!l||!h)return!1;if("video"==h)return g.duration;
if("youtube"==h)return p.getDuration()};this.getLoadProgress=function(){if(!l||!h)return!1;var a;if("video"==h){if("undefined"!==typeof g.buffered&&0!=g.buffered.length){try{var b=g.buffered.end(g.buffered.length-1)}catch(ra){}isNaN(b)||(a=b/Math.floor(g.duration))}}else"youtube"==h&&(a=p.getVideoLoadedFraction());return a};this.togglePlaylist=function(a){if(!l)return!1;Kc(a)};this.toggleRandom=function(a){if(!l||"undefined"===typeof y)return!1;y.setRandom(a)};this.toggleLoop=function(a){if(!l||"undefined"===
typeof y)return!1;y.setLooping(a)};this.setPlaybackRate=function(a){if(!l||!h)return!1;k.playbackRate=a;"video"==h?g&&(g.playbackRate=a):"youtube"==h&&p.setPlaybackRate(a)};this.setPlaybackQuality=function(a){if(!l||!h)return!1;"image"==h||"video"==h?"hls"!=G&&(k.quality=a,H(a),sb(!0)):"youtube"==h&&p.setPlaybackQuality(a)};this.toggleInfo=function(a){if(!l||!h)return!1;Sa(a)};this.toggleShare=function(a){if(!l||!h)return!1;xa(a)};this.toggleFullscreen=function(){if(!l)return!1;la.click()};this.destroyMedia=
function(){if(!l)return!1;l&&h&&(ia(),tc(),y.reSetCounter())};this.destroyPlaylist=function(){if(!l)return!1;Mc()};this.loadPlaylist=function(a){if(!l||vb)return!1;if("string"===typeof a){if(pc==a)return!1;rb(a)}else return alert("Invalid value loadPlaylist!"),!1};this.loadMedia=function(a){if(!l||vb||!Tb)return!1;if("number"===typeof a)0>a?a=0:a>L-1&&(a=L-1),y.processPlaylistRequest(a);else return alert("Invalid value loadMedia!"),!1};this.getMediaPlaying=function(){return l?S:!1};this.getSetupDone=
function(){return l};this.getActiveItemId=function(){return l?"undefined"!==typeof y?y.getCounter():null:!1};c.activePlaylist&&!MVPUtils.isEmpty(c.activePlaylist)?rb(c.activePlaylist):hd();return this}})(jQuery);